POST http://localhost:3000/hook HTTP/1.1
Content-Type: application/json

{
    "event_id":"01ED4N7C365KM81QQ5A1AHGKRQ",
    "event_type":"form_response",
    "form_response":{
        "form_id":"tK72VL",
        "token":"l4g18m2mfqupgeb9ehl4g1ogshrixojt",
        "landed_at":"2020-07-13T17:57:09Z",
        "submitted_at":"2020-07-13T17:58:08Z",
        "hidden":{
        "eo":"6",
        "eot":"20",
        "gr":"7",
        "grt":"200", 
        "hl":"15",
        "ht":"12",
        "lt":"12",
        "name":"test",
        "tr":"8",
        "trt":"less than RM10"
        },
        "definition":{
        "id":"tK72VL",
        "title":"Recommend Engine - Cat. Demograhic",
        "fields":[
            {
                "id":"zJCOvbLPsuEU",
                "title":"How much of your income do you save?",
                "type":"multiple_choice",
                "ref":"02ff5dee-7d05-48d8-81c9-95bd7a2e1af1",
                "properties":{

                },
                "choices":[
                    {
                    "id":"PKVWWKIriF6z",
                    "label":"I don't have enough to save"
                    },
                    {
                    "id":"lqWRkH1ZNHva",
                    "label":"Quarter of my income"
                    },
                    {
                    "id":"b9pyqE9oeseH",
                    "label":"Half of my income"
                    },
                    {
                    "id":"LoDoZrrBROyG",
                    "label":"More than half of my income"
                    },
                    {
                    "id":"TO4bGFbEjWvT",
                    "label":"I'm not sure"
                    }
                ]
            },
            {
                "id":"blQ7puikpG8H",
                "title":"Can you afford an unexpected expense of RM1,000",
                "type":"multiple_choice",
                "ref":"366670a4-a86d-49a8-8979-872eb626abd3",
                "properties":{

                },
                "choices":[
                    {
                    "id":"M3Sa5iHDKLrp",
                    "label":"Yes"
                    },
                    {
                    "id":"aiQqOEWIaAcC",
                    "label":"No"
                    }
                ]
            },
            {
                "id":"koqve230Ssg1",
                "title":"What's your age range?",
                "type":"multiple_choice",
                "ref":"7085ebec9237ffda",
                "properties":{

                },
                "choices":[
                    {
                    "id":"meRTvbMgcbca",
                    "label":"18 or younger"
                    },
                    {
                    "id":"RyJAcbfbkJRi",
                    "label":"19 - 24"
                    },
                    {
                    "id":"MIPJfs9YRWHQ",
                    "label":"25 - 34"
                    },
                    {
                    "id":"LMbXEmwF3YsO",
                    "label":"35 - 44"
                    },
                    {
                    "id":"wp6NkAehBLaI",
                    "label":"45 - 54"
                    },
                    {
                    "id":"A1uFh5zSWjKG",
                    "label":"55 - 64"
                    },
                    {
                    "id":"K1wWIbKNM2Ac",
                    "label":"65 or older"
                    }
                ]
            },
            {
                "id":"x9KJyPqqB7r3",
                "title":"...and your monthly income range?",
                "type":"multiple_choice",
                "ref":"9c813b06196b1091",
                "properties":{

                },
                "choices":[
                    {
                    "id":"p4P0uputDoXG",
                    "label":"RM2,000 or less"
                    },
                    {
                    "id":"xIHHqdp64QmC",
                    "label":"RM2,001 - RM4,000"
                    },
                    {
                    "id":"ppsIdbVGkGi9",
                    "label":"RM4,001 - RM6,000"
                    },
                    {
                    "id":"fG2WGb5pRcRt",
                    "label":"RM6,001 - RM8,000"
                    },
                    {
                    "id":"OyI6SvhJcGcW",
                    "label":"More than RM8,000"
                    },
                    {
                    "id":"i0B32D4SY4nT",
                    "label":"I prefer not to answer"
                    }
                ]
            },
            {
                "id":"Q8hgGZX4qNqd",
                "title":"What's your current employment status?",
                "type":"multiple_choice",
                "ref":"371d2026ca0a48c3",
                "properties":{

                },
                "choices":[
                    {
                    "id":"kqHM1cDr77YV",
                    "label":"Employed full-time"
                    },
                    {
                    "id":"mvPezlVmLp7r",
                    "label":"Employed part-time"
                    },
                    {
                    "id":"mMQBrDK2D2GO",
                    "label":"Self-employed"
                    },
                    {
                    "id":"kpcRhccqRzWh",
                    "label":"Unemployed"
                    },
                    {
                    "id":"bT3uoXToW6zW",
                    "label":"Not looking for work"
                    },
                    {
                    "id":"BCV9enq60R8R",
                    "label":"Gig-worker"
                    },
                    {
                    "id":"EMuDe2bOjNXQ",
                    "label":"Retired"
                    },
                    {
                    "id":"sbHp531KByO4",
                    "label":"Student"
                    },
                    {
                    "id":"hjqAyxBc4boB",
                    "label":"I prefer not to answer"
                    }
                ]
            },
            {
                "id":"TPFtoDhXcrJ1",
                "title":"What's the highest level of education you've completed?",
                "type":"multiple_choice",
                "allow_other_choice":true,
                "ref":"f2e07dfef223e66d",
                "properties":{

                },
                "choices":[
                    {
                    "id":"NWyRdYRQ2aiv",
                    "label":"Less than High School"
                    },
                    {
                    "id":"Nu9Yq3wy0Zbq",
                    "label":"High School"
                    },
                    {
                    "id":"hQHGiEVuyTSq",
                    "label":"Some College / University"
                    },
                    {
                    "id":"Nw0Tqs3CyZsd",
                    "label":"College Diploma / Certificate"
                    },
                    {
                    "id":"dAd6y2KsPYoC",
                    "label":"Undergraduate Degree"
                    },
                    {
                    "id":"KY2YjEH8ipPL",
                    "label":"Masters / Graduate Degree"
                    },
                    {
                    "id":"Gx8Dnxrb9wG5",
                    "label":"Doctorate"
                    },
                    {
                    "id":"PsK9CCd6oXul",
                    "label":"I prefer not to answer"
                    }
                ]
            },
            {
                "id":"rGuxY2m9lKzk",
                "title":"Are you currently taking any loans?",
                "type":"multiple_choice",
                "ref":"39d4143e-0ebf-4bbf-bfa0-611566b0fc9c",
                "properties":{

                },
                "choices":[
                    {
                    "id":"WIE7b2j64RXa",
                    "label":"Yes"
                    },
                    {
                    "id":"lB8opmFBbvm9",
                    "label":"No"
                    }
                ]
            },
            {
                "id":"pSmsF7MPrfOT",
                "title":"If so, what kind of loan?",
                "type":"multiple_choice",
                "allow_multiple_selections":true,
                "ref":"f76d2215-981a-4409-b92e-122f34c5b5a3",
                "properties":{

                },
                "choices":[
                    {
                    "id":"ZpeTiO4rgCvg",
                    "label":"Housing loan"
                    },
                    {
                    "id":"ZPFSik7MH1Oi",
                    "label":"Car loan"
                    },
                    {
                    "id":"K2tKg9CeyyNO",
                    "label":"Educational loan"
                    },
                    {
                    "id":"EcvRehlm2F4F",
                    "label":"Personal loan"
                    }
                ]
            },
            {
                "id":"NlXHIFWaN8xY",
                "title":"How many percent of your monthly income is used to service your loans?",
                "type":"multiple_choice",
                "ref":"307ceb51-e1e8-4620-8319-6eecff75d7ad",
                "properties":{

                },
                "choices":[
                    {
                    "id":"hjGb6gySNtQC",
                    "label":"Lower than 20%"
                    },
                    {
                    "id":"LAwrPGGaNPxw",
                    "label":"20%-40%"
                    },
                    {
                    "id":"wqkVQ3WFgY9B",
                    "label":"More than 40%"
                    },
                    {
                    "id":"TG3qOWOCcQDI",
                    "label":"I prefer not to answer"
                    }
                ]
            },
            {
                "id":"MMBD8ew3CQUR",
                "title":"We're curious to know, which state are you from?",
                "type":"dropdown",
                "ref":"c134cfca-b875-4469-9ea1-9c399bee2c03",
                "properties":{

                }
            },
            {
                "id":"vn1nuUXmieat",
                "title":"Where in Kedah are you from?",
                "type":"dropdown",
                "ref":"a26225e2-fa17-49dc-8ab0-9158f55eebd0",
                "properties":{

                }
            },
            {
                "id":"iXqDE7CFEbDC",
                "title":"Drop us your email so we can send you the report!",
                "type":"email",
                "ref":"c2920f4f-3280-416a-b6e3-25e36361e8c4",
                "properties":{

                }
            }
        ]
        },
        "answers":[
        {
            "type":"choice",
            "choice":{
                "label":"I don't have enough to save"
            },
            "field":{
                "id":"zJCOvbLPsuEU",
                "type":"multiple_choice",
                "ref":"02ff5dee-7d05-48d8-81c9-95bd7a2e1af1"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Yes"
            },
            "field":{
                "id":"blQ7puikpG8H",
                "type":"multiple_choice",
                "ref":"366670a4-a86d-49a8-8979-872eb626abd3"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"18 or younger"
            },
            "field":{
                "id":"koqve230Ssg1",
                "type":"multiple_choice",
                "ref":"7085ebec9237ffda"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"RM2,000 or less"
            },
            "field":{
                "id":"x9KJyPqqB7r3",
                "type":"multiple_choice",
                "ref":"9c813b06196b1091"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Employed full-time"
            },
            "field":{
                "id":"Q8hgGZX4qNqd",
                "type":"multiple_choice",
                "ref":"371d2026ca0a48c3"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Less than High School"
            },
            "field":{
                "id":"TPFtoDhXcrJ1",
                "type":"multiple_choice",
                "ref":"f2e07dfef223e66d"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Yes"
            },
            "field":{
                "id":"rGuxY2m9lKzk",
                "type":"multiple_choice",
                "ref":"39d4143e-0ebf-4bbf-bfa0-611566b0fc9c"
            }
        },
        {
            "type":"choices",
            "choices":{
                "labels":[
                    "Housing loan"
                ]
            },
            "field":{
                "id":"pSmsF7MPrfOT",
                "type":"multiple_choice",
                "ref":"f76d2215-981a-4409-b92e-122f34c5b5a3"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Lower than 20%"
            },
            "field":{
                "id":"NlXHIFWaN8xY",
                "type":"multiple_choice",
                "ref":"307ceb51-e1e8-4620-8319-6eecff75d7ad"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Kedah"
            },
            "field":{
                "id":"MMBD8ew3CQUR",
                "type":"dropdown",
                "ref":"c134cfca-b875-4469-9ea1-9c399bee2c03"
            }
        },
        {
            "type":"choice",
            "choice":{
                "label":"Alor Setar"
            },
            "field":{
                "id":"vn1nuUXmieat",
                "type":"dropdown",
                "ref":"a26225e2-fa17-49dc-8ab0-9158f55eebd0"
            }
        },
        {
            "type":"email",
            "email":"test@email.com",
            "field":{
                "id":"iXqDE7CFEbDC",
                "type":"email",
                "ref":"c2920f4f-3280-416a-b6e3-25e36361e8c4"
            }
        }
        ]
    }
}